### ISSUE TITLE
Is it latest version of GNU classpath?

### ISSUE THREAD

**Issue by stokito** [penberg/classpath#1]
Hi,
It looks like GNU classpath is abandoned but in the same time I found it's source code more clear and easier to understood. Also it looks like some small JVMs are using it because of small footprint.
It think this is very actual in light of IoT revolution. 
The [last commit](https://cvs.savannah.gnu.org/viewvc/classpath/classpath/ChangeLog?view=log) was  2012 Mar 29 but in your fork it looks like you have commits after that i.e. 2013 May 26 and from the same authors who contributed to classpath.
So can I assume that your fork is actually latest version of GNU classpath?
Maybe it worst to write to dev list with proposition to migrate official repository to Github and merge with your fork?
Thank you

**Comment by penberg** [comment]
Latest GNU Classpath can be found in the project git repository here:

http://git.savannah.gnu.org/cgit/classpath.git
